// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutPage: typeof import('./components/pages/AboutPage.vue')['default']
    EditEvent: typeof import('./components/EditEvent.vue')['default']
    EventEditPage: typeof import('./components/pages/EventEditPage.vue')['default']
    EventPage: typeof import('./components/pages/EventPage.vue')['default']
    HomePage: typeof import('./components/pages/HomePage.vue')['default']
    LegalPage: typeof import('./components/pages/LegalPage.vue')['default']
    LoginCallbackPage: typeof import('./components/pages/LoginCallbackPage.vue')['default']
    LoginPage: typeof import('./components/pages/LoginPage.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    NavBar: typeof import('./components/nav/NavBar.vue')['default']
    ProfileEditPage: typeof import('./components/pages/ProfileEditPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/nav/SideBar.vue')['default']
    SiteLogo: typeof import('./components/SiteLogo.vue')['default']
  }
}
