// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AboutPage: typeof import('./components/pages/AboutPage.vue')['default']
    EditEvent: typeof import('./components/EditEvent.vue')['default']
    EventEditPage: typeof import('./components/pages/EventEditPage.vue')['default']
    EventPage: typeof import('./components/pages/EventPage.vue')['default']
    HomePage: typeof import('./components/pages/HomePage.vue')['default']
    LoginModal: typeof import('./components/LoginModal.vue')['default']
    LoginPage: typeof import('./components/pages/LoginPage.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    ProfileEditPage: typeof import('./components/pages/ProfileEditPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheNavBar: typeof import('./components/nav/TheNavBar.vue')['default']
    TheSideBar: typeof import('./components/nav/TheSideBar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanDatePicker: typeof import('vant/es')['DatePicker']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTimePicker: typeof import('vant/es')['TimePicker']
  }
}
