// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AboutPage: typeof import("./components/pages/AboutPage.vue")["default"];
    Countdown: typeof import("./components/Countdown.vue")["default"];
    EditEvent: typeof import("./components/EditEvent.vue")["default"];
    EventCreatePage: typeof import("./components/pages/EventCreatePage.vue")["default"];
    EventDashboard: typeof import("./components/pages/EventDashboard.vue")["default"];
    EventEditPage: typeof import("./components/pages/EventEditPage.vue")["default"];
    EventInfo: typeof import("./components/EventInfo.vue")["default"];
    EventListItem: typeof import("./components/EventListItem.vue")["default"];
    EventPage: typeof import("./components/pages/EventPage.vue")["default"];
    EventSearchPage: typeof import("./components/pages/EventSearchPage.vue")["default"];
    HomePage: typeof import("./components/pages/HomePage.vue")["default"];
    LegalPage: typeof import("./components/pages/LegalPage.vue")["default"];
    LoginCallbackPage: typeof import("./components/pages/LoginCallbackPage.vue")["default"];
    LoginPage: typeof import("./components/pages/LoginPage.vue")["default"];
    MatchesPage: typeof import("./components/pages/MatchesPage.vue")["default"];
    ProfileEditPage: typeof import("./components/pages/ProfileEditPage.vue")["default"];
    RegistrationOverview: typeof import("./components/RegistrationOverview.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SideBar: typeof import("./components/SideBar.vue")["default"];
    SiteLogo: typeof import("./components/SiteLogo.vue")["default"];
    SkeletonLoader: typeof import("./components/SkeletonLoader.vue")["default"];
    TimeDisplay: typeof import("./components/TimeDisplay.vue")["default"];
  }
}
